website/models.py
from . import db    #"." is website(package h isliye naam likhne ki need nhi h)
from flask_login import UserMixin   #what is this?
from sqlalchemy.sql import func

class Note(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    #how you associate different notes to different users(relationship between Note and User[foreign key])
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))   #we must pass a valid user_id to access/write notes(oneToMany relationship; one=user, many=notes)

#Learn how to pass media(images, videos) by watching SQLAlchemy tutorial
#learn all types of relationships(one-to-many, many-to-one, many-to-many, one-to-one)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique = True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship('Note') #it will be a list that will store different notes(we are referencing name of the class)
    

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
#db is the db object we will use whenever we want to add something to the db
db = SQLAlchemy()
DB_NAME = "database.db"
def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'asdf qwer zxcv'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'   #sqlite is stored at this location
    db.init_app(app)
    
    from .views import views
    from .auth import auth
    
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    
    from .models import User, Note
    
    create_database(app)
    
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    
    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        with app.app_context():
            db.create_all()
            print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
#CREATING NEW ACCOUNTS
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db

#FLASK LOGIN MODULE 
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You have been logged out successfully!", category='success')
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    #differentiating between a GET request and a POST request
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        
        user = User.query.filter_by(email=email).first()
        if user:
            flash('User already exists', category='error')
        #update with small alphabet, capital alphabet, number and a special character
        elif len(email) < 4:
            flash('Email must be greater than 3 characters', category='error')
        elif len(first_name) < 2:
            flash('First Name must be greater than 1 character', category='error')
        elif password1 != password2:
           flash('Passwords do not match', category='error')
        elif len(password1) < 7:
           flash('Password is too short', category='error')
        else:
            #creating new user accounts
            new_user = User(email=email, first_name = first_name, password=generate_password_hash(password1, method='pbkdf2:sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))
            # add user to the database
    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user

from .models import Note, User
from . import db

import json

views = Blueprint('views', __name__)

@views.route('/', methods = ['GET','POST'])
@login_required
def home():
    if request.method == 'POST':
        note = request.form.get('note')
        
        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')
    return render_template("home.html", user=current_user)

@views.route('/delete-note/<int:id>', methods=['POST'])
@login_required
def delete_note(id):
    note = Note.query.get_or_404(id)

    if note.user_id != current_user.id:
        flash("You do not have permission to delete this note.", category='error')
        return redirect(url_for('views.home'))

    db.session.delete(note)
    db.session.commit()
    flash("Note deleted successfully.", category='success')
    return redirect(url_for('views.home'))

'''
@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
            
    return jsonify({})

'''
    

website/templates/base.html
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Home{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
    <!--CS bootstrap links-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />
    </body>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <!--code for expanding the navbar on smaller devices/screen-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                {% else %}
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signup" href="/sign-up">Sign up</a>
                {% endif %}
            </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category =='error' %}
    <!--error message-->
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aira-hidden="true">&times;</span>
        </button>
    </div>
    <!--success message-->
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aira-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!--JS bootstrap links-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}

{% block content %}
<h1 align="center">Notes</h1>
<ul class="list-group list-group-flush">
    {% for note in user.notes %}
    <li class="list-group-item" style="position: relative; padding-right: 40px;"> <!-- extra space for icon -->
        {{ note.data }}
        <form method="POST" action="{{ url_for('views.delete_note', id=note.id) }}"
            style="position: absolute; top: 50%; right: 10px; transform: translateY(-50%); margin: 0; padding: 0;">
            <button type="submit"
                style="border: none; background: none; color: red; font-size: 20px; cursor: pointer; font-weight: bold;"
                title="Delete note">
                &times;
            </button>
        </form>
    </li>
    {% endfor %}
</ul>
<form method="POST">
    <textarea name="note" id="note" class="form-control"></textarea>
    <br>
    <div align="center">
        <button type="submit" class="btn btn-primary">Add Note</button>
    </div>
</form>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}

{% block content %}
<form method="POST">
    <br>
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email: </label>
        <input 
            type="email" 
            class="form-control" 
            id="email" 
            name="email" 
            placeholder="Enter email"
        />
    </div>

    <div class="form-group">
        <label for="password">Password: </label>
        <input 
            type="password" 
            class="form-control" 
            id="password" 
            name="password" 
            placeholder="Enter password"
        />
    </div>

    <br>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Home{% endblock %}

{% block content %}
<form method="POST">
    <br>
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
        <label for="email">Email: </label>
        <input 
            type="email" 
            class="form-control" 
            id="email" 
            name="email" 
            placeholder="Enter email"
        />
    </div>

    <div class="form-group">
        <label for="firstName">First Name: </label>
        <input 
            type="text" 
            class="form-control" 
            id="firstName" 
            name="firstName" 
            placeholder="Enter first name"
        />
    </div>
<!--
<div class="form-group">
        <label for="lastName">Last Name: </label>
        <input 
            type="text" 
            class="form-control" 
            id="lastName" 
            name="lastName" 
            placeholder="Enter last name"
        />
    </div>
-->

    <div class="form-group">
        <label for="password1">Password: </label>
        <input 
            type="password" 
            class="form-control" 
            id="password1" 
            name="password1" 
            placeholder="Enter password"
        />
    </div>

    <div class="form-group">
        <label for="password2">Password: </label>
        <input 
            type="password" 
            class="form-control" 
            id="password2" 
            name="password2" 
            placeholder="Confirm password"
        />
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}